package com.course.springdata.intro.entity;

public enum Color {
    BLUE,RED,PURPLE,YELLOW,PINK,GREEN,
    ORANGE,LIME,AQUA,NAVY,CORAL,TEAL,
    MUSTARD,BLUE_VIOLET,BLACK,WHITE,
    GREY,BROWN,DARK_GREEN,BLUE_GRAY,
    INDIGO,PEA_GREEN,ABMER,PEACH,MAROON;
}
